FROM demiddleday3_jupyter:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /elasticsearch

WORKDIR /elasticsearch

EXPOSE 8889

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8889 --no-browser