FROM jupyter/pyspark-notebook:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /pyspark

WORKDIR /pyspark

EXPOSE 8888

RUN jupyter notebook --generate-config -y --allow-root

RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser